name: Daily Commit

on:
  schedule:
    - cron: "0 12 * * *"  # Executa todo dia às 12h UTC (09h no Brasil)
  workflow_dispatch:       # Permite rodar manualmente
jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Adicionar commit automático
        run: |
          echo "Atualização automática em $(date)" >> log.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add log.txt
          git commit -m "Auto commit: $(date)" || echo "Sem alterações"
          git push
